### PR TITLE
add module payment_alipay

### PR DESCRIPTION
**Pull request by Rona111**

### CODE REVIEW

**Comment by duanyp1991** [comment]
LGTM

**Comment by elicoidal** [comment]
This one should be proposed later to OCA. Maybe do it now?

**Comment by noahzaozao** [comment]
@elicoidal @seb-elico For alipay , since the PR OCA/l10n-china are not able to merge , https://github.com/OCA/l10n-china/pull/21 , shall we merge this PR? I'll create new PR with my changes after this one.

**Comment by seb-elico** [comment]
@noahzaozao what do you mean, not able to merge? Even if it's not merged, we can still pull the code. So the OCA one should remain our target. We should close this one IMO.

**Comment by elicoidal** [comment]
I will push to be able to merge.

**Comment by noahzaozao** [comment]
@elicoidal @seb-elico https://github.com/OCA/l10n-china/pull/21 Please use this PR , it's latest alipay module.

**Comment by elicoidal** [comment]
@noahzaozao can you close all other unnecessary ones?

**Comment by elicoidal** [comment]
I propose to close this one as this is a duplicate of OCA

**Pull request closed without merging**
