### PR TITLE
[IMP]add payroll model for v9.

### PR DESCRIPTION
**Pull request by Rona111**

### CODE REVIEW

**Comment by victor-ditay** [comment]
@elicoidal @seb-elico @noahzaozao Since is V9 later we should wait to test and review after migration. There is no information on any test (Travis is just missing the file).

**Comment by elicoidal** [comment]
You need to make sure this is the latest module. IMO ther eis a similar module in OCA

**Comment by victor-ditay** [comment]
> You need to make sure this is the latest module. IMO ther eis a similar module in OCA

@elicoidal You are right this is the latest one version on OCA 9.0 repository:
https://github.com/OCA/l10n-china/pull/9

**Comment by elicoidal** [comment]
@victormartinelicocorp Can you review the one in OCA so that we can merge it?
I will close this one

**Comment by victor-ditay** [comment]
Done

**Pull request closed without merging**
