### PR TITLE
11437 migrate the elico8 module from v8 to v9 language switch

### PR DESCRIPTION
**Pull request by Rona111**

### CODE REVIEW

**Comment by elicoidal** [comment]
LGTM

**Comment by siyuancn** [comment]
@Rona111 Did you test it in the https?

**Comment by Rona111** [comment]
@siyuancn  no,I will sent you the module and please help me to put them in the trunk.Tks.

**Comment by siyuancn** [comment]
@Rona111 The testing environment is odoo 8.0.
@elicoidal Should I create an odoo9 enterprise environment for the testing?

**Comment by Rona111** [comment]
@elicoidal @siyuancn  yes ,need odoo9 env,but I am not sure enterprise or community.

**Comment by elicoidal** [comment]
probably 9c is good enough.

**Comment by victor-ditay** [comment]
@elicoidal @seb-elico @noahzaozao I think this on could be optimistic merged.

**Comment by seb-elico** [comment]
@victormartinelicocorp we first need to make sure it passes Travis (PEP8, OCA guidelines)

**Comment by elicoidal** [comment]
@seb-elico agree. All modules in v9 must be compliant

**Comment by seb-elico** [comment]
@elicoidal and have UT, 100% cover, use new API, etc.

**Comment by victor-ditay** [comment]
> @victormartinelicocorp we first need to make sure it passes Travis (PEP8, OCA guidelines)

@seb-elico Could you add travis file also for the 9.0 master branch?

**Comment by seb-elico** [comment]
@victormartinelicocorp done. However, let's focus on the v8 modules for now, so that we can clean them once and for all. Later, we will migrate (some of) them to v9 !

**Comment by victor-ditay** [comment]
> @victormartinelicocorp done. However, let's focus on the v8 modules for now, so that we can clean them once and for all. Later, we will migrate (some of) them to v9 !

Ok

**Comment by elicoidal** [comment]
@victormartinelicocorp can you make sure to cleanse this module and move forward?
Maybe a candidate for OCA/web

**Pull request closed without merging**
