### PR TITLE
Add property managment modules

### PR DESCRIPTION
**Pull request by seb-elico**

### CODE REVIEW

**Comment by elicoidal** [comment]
@seb-elico I think this is the code that we bought to SCS for property management.
I don t see the point of pushing it here: rather have a private repo and reuse it for our SaaS if necessary.

**Comment by seb-elico** [comment]
@elicoidal I have the following TMS on 151208:

> Supervise migration from GitLab to GitHub: Create PR on Elico public GitHub with property module source code

I don't recall why we decided to put it here. Maybe you suggested to make the module public due to the license and the fact that we bought it.

Anyway, this is not the right repo. This repo is for addons created by Elico. Since we are not the author, we have 2 repos for addons that could be suitable:

- https://github.com/Elico-Corp/odoo-community-addons: public third-party addons not available on GH
- https://github.com/Elico-Corp/odoo-private-addons: private third-party addons

Based on your previous message, I would say the 2nd one.

**Comment by elicoidal** [comment]
Actually I would prefer to have them as one repo as they are a set of module.
Please create a separate private repo (if not enough, I suggest to remove and archive all MMX content except public one)

**Comment by elicoidal** [comment]
@seb-elico Still OK to move to one specific repo?

**Comment by seb-elico** [comment]
@elicoidal IMO our odoo-community-addons repo is the most suitable for these modules. To be noted that 2 out of 5 modules are not linked to property management (popup_reminder and web_o2m_multi_delete).

Also why do you mention MMX in your previous message?

**Pull request closed without merging**
