### PR TITLE
add module web_easy_switch_company

### PR DESCRIPTION
**Pull request by Rona111**

### CODE REVIEW

**Comment by elicoidal** [comment]
This is a community module: do we need to push to our repo?

**Comment by Rona111** [comment]
@elicoidal besides you pointed these two modules,web_export_view is also a OCA modules.
I am not sure whether it should be our repo or not.

**Comment by elicoidal** [comment]
no need: use directly the original repo. no duplication

**Comment by duanyp1991** [comment]
@Rona111  delete this PR, this module is from OCA.

**Comment by Rona111** [comment]
yes,this module is from oca.should i delete it? @elicoidal @seb-elico @duanyp1991 @siyuancn

**Comment by elicoidal** [comment]
yes

**Comment by Rona111** [comment]
OCA module,delete.

**Pull request closed without merging**
