### PR TITLE
[10.0][COMMUNITY]Add test case for module business_requirement_deliverable_project_task_mandatory

### PR DESCRIPTION
**Pull request by Sunnyshine008**
add test case

### CODE REVIEW

**Review by elicoidal — CHANGES_REQUESTED** [review]
LGTM.
Add your name as contributor
Bump version number follwing: https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#version-numbers

**Comment by elicoidal** [comment]
Travis is complaining too

**Comment by Sunnyshine008** [comment]
@Elico-Corp/odoo-reviewers

**Comment by elicoidal** [comment]
Nothing new since last commit

**Comment by JoJoJoJoJoJoJo** [comment]
Replaced by #227, please close the pr. @Elico-Corp/odoo-reviewers

**Pull request closed without merging**
