### PR TITLE
fix wrong display of partner ref in project searching

### PR DESCRIPTION
**Pull request by franksongfeng**

### CODE REVIEW

**Comment by franksongfeng** [comment]
submit fix to the function name_get() of the model "project.project", the file "property_partner_mandatory.py"

**Comment by franksongfeng** [comment]
fix bug in the function get_name() in the model project.project, in project_partner_mandatory.py

**Comment by franksongfeng** [comment]
@seb-elico @noahzaozao @elicoidal @victormartinelicocorp @xuan139 pls review

**Comment by elicoidal** [comment]
:+1: 
@seb-elico @noahzaozao @victormartinelicocorp @xuan139 pls review

**Comment by noahzaozao** [comment]
LGTM

**Comment by xuan139** [comment]
LGTM

**Pull request merged**
