### PR TITLE
10.0-MIG-T23292-BR001145-Migrate-project_issue_sheet_issue_detail-module-to-v10

### PR DESCRIPTION
**Pull request by murtuzasaleh**
WIP

### CODE REVIEW

**Comment by murtuzasaleh** [comment]
@elicoidal @victormartinelicocorp Please Review it.

**Comment by victor-ditay** [comment]
@murtuzasaleh which document or reference are you following? At least we have a BR related and couldn't find any reference

**Comment by murtuzasaleh** [comment]
@victormartinelicocorp I am following https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0 document.

**Comment by victor-ditay** [comment]
Name of PR: 
[MIG][10.0-Issue175-T23292]: Migrated project_issue_sheet_issue_detail module. #184

should be:
10.0-MIG-T23292-BR001145-Migrate-project_issue_sheet_issue_detail-module-to-v10

**Comment by murtuzasaleh** [comment]
@victormartinelicocorp Ok, I will change it.

**Comment by victor-ditay** [comment]
@murtuzasaleh please rebase. I have made changes on Travis.

**Review by elicoidal — APPROVED** [review]
LGTM

**Review by victor-ditay — APPROVED** [review]
To be tested.

**Comment by iceyxu** [comment]
@elicoidal  Who will do test?

**Comment by elicoidal** [comment]
@iceyxu We need to tests all these features but runbot is not yet ready. 
I would suggest that @victormartinelicocorp prepare the trunk environment for Elico with latest modifications and that you test them

**Comment by victor-ditay** [comment]
> @iceyxu We need to tests all these features but runbot is not yet ready.
I would suggest that @victormartinelicocorp prepare the trunk environment for Elico with latest modifications and that you test them

@elicoidal I would check with @seb-elico the necessary setup, but anyway then should we merge this PR for test it or should I deploy PR by PR and create new DB's with demo data?

**Pull request merged**
