### PR TITLE
[FIX] remove task_categ_id field in graph view

### PR DESCRIPTION
**Pull request by noahzaozao**

### CODE REVIEW

**Comment by noahzaozao** [comment]
@Elico-Corp/odoo-reviewers Please review this pr

**Comment by elicoidal** [comment]
LGTM

**Comment by elicoidal** [comment]
Is travis supposed to failed?
@noahzaozao

**Comment by seb-elico** [comment]
@elicoidal Travis is most definitely supposed to fail. This is the v8 repo of our public addons, we said we would focus on OCA compliance for future versions.

@noahzaozao LGTM, next step is to add it back but to use the task category coming from the task tag! To do in a separate PR

**Pull request merged**
