### PR TITLE
[IMP]add v9 website_certificate.

### PR DESCRIPTION
**Pull request by Rona111**

### CODE REVIEW

**Comment by elicoidal** [comment]
check 8.0 review. LGTM

**Comment by siyuancn** [comment]
LGTM

**Comment by elicoidal** [comment]
there is no UT. Do we need them for such kind of simple module?

**Comment by siyuancn** [comment]
No unit test for this module since it's for the .py file.

**Comment by elicoidal** [comment]
OK. LGTM

**Pull request merged**
