### PR TITLE
[FIX] stock_pmc_report: Fix travis on 8.0 branch, links others Travis…

### PR DESCRIPTION
**Pull request by victor-ditay**
… test fails.

```
modified:   stock_pmc_report/wizard/stock_inventory_report.py
```

### CODE REVIEW

**Comment by victor-ditay** [comment]
@elicoidal @seb-elico @noahzaozao

**Comment by elicoidal** [comment]
TRavis still failing ( @victormartinelicocorp )

**Comment by elicoidal** [comment]
@victormartinelicocorp can you fix the conflicts so that we merge?
v8=>no need tests/travis

**Comment by victor-ditay** [comment]
> @victormartinelicocorp can you fix the conflicts so that we merge?
v8=>no need tests/travis

@elicoidal This module doesn't exist anymore. @noahzaozao Do you know if was re-factored?

cc @seb-elico @xuan139

**Comment by elicoidal** [comment]
@victormartinelicocorp Strange. Anyway it should be available in Xebon project AFAIR

**Comment by seb-elico** [comment]
@victormartinelicocorp you mean the module is not in the repo anymore?

**Comment by victor-ditay** [comment]
> @victormartinelicocorp you mean the module is not in the repo anymore?

Yes

**Pull request merged**
