### PR TITLE
[FIX] 8.0 traivs issue

### PR DESCRIPTION
**Pull request by noahzaozao**

### CODE REVIEW

**Review by elicoidal — APPROVED** [review]
:+1: 
@seb-elico @victormartinelicocorp

**Comment by elicoidal** [comment]
Travis still failing: any reason?

**Comment by noahzaozao** [comment]
@elicoidal It has been fixed last Friday , then because you merged a few failed PR into this branch yesterday.

**Comment by elicoidal** [comment]
OK: @noahzaozao my bad. I thought we did not care of Travis for v8.0...
Can you fixed the merged PR from yesterday and we keep the good habit of green PR even for v8?
If too complicated then I just revert the merges

**Comment by noahzaozao** [comment]
except_orm: ('Error', u"You try to install module 'product_cost' that depends on module 'report_xls'.\nBut the latter module is not available in your system.")

**Comment by elicoidal** [comment]
report_xls is a OCA module AFAIK @noahzaozao

**Comment by noahzaozao** [comment]
after I fixed one , another one appeared , still trying to fix travis

**Comment by noahzaozao** [comment]
@elicoidal @seb-elico please review , I've fixed the travis again.

**Review by elicoidal — APPROVED** [review]

**Comment by elicoidal** [comment]
@seb-elico @victormartinelicocorp

**Comment by noahzaozao** [comment]
@Elico-Corp/odoo-reviewers

**Comment by xuan139** [comment]
LGTM

**Pull request merged**
