### PR TITLE
[ADD] payment_wcpay 8.0

### PR DESCRIPTION
**Pull request by xie8899**

### CODE REVIEW

**Comment by elicoidal** [comment]
PR should be done in OCA/l10n-China

**Comment by duanyp1991** [comment]
@elicoidal  Im confused here: PRs to oca has been made long time ago.
I though you want to put this module to this module to be able to publish on the apps.odoo.com.

**Comment by elicoidal** [comment]
AFAIK only the v9 has been pulled to OCA, not version 8

**Comment by duanyp1991** [comment]
ok, so I'll let Rona to push the wechat pay v8 to oca.

**Pull request closed without merging**
