### PR TITLE
add module website_slides

### PR DESCRIPTION
**Pull request by Rona111**

### CODE REVIEW

**Comment by duanyp1991** [comment]
Delete this PR, this module is from odoo @Rona111

**Comment by elicoidal** [comment]
Actually this is a backport and there is a PR somewhere but not sure in 
the OCA. If not, propose directly to OCA

**Comment by Rona111** [comment]
cc @elicoidal @seb-elico @duanyp1991 @siyuancn This module is a oca module.

**Comment by Rona111** [comment]
should we push this module to odoo repo?

**Comment by seb-elico** [comment]
AFAIR, @siyuancn fixed a bug inside the module but the fix wasn't completely satisfactory. We should double-check what's the remaining issue and create a PR on the OCA project. Temporarily we can keep the code inside this PR until we get this sorted out.

**Comment by elicoidal** [comment]
@seb-elico @siyuancn We need to debug it asap as this impact our image
I would push it to OCA once completely debug

**Comment by siyuancn** [comment]
@elicoidal I will check it asap

**Comment by siyuancn** [comment]
@elicoidal @seb-elico @Rona111  This module is used to solve the pdf uploading issue for the website_slide
I checked the module (v9) in my local. Both documentation and youtube video work well. 
I think we dont' need this module again.

**Comment by elicoidal** [comment]
@siyuancn this is a backport for v8 so we need it in v8. In v9, we just need the qq one

**Comment by siyuancn** [comment]
@elicoidal ok
@Rona111 please check the official module in V9 to make sure there is no difference.

**Comment by noahzaozao** [comment]
@elicoidal @seb-elico @victormartinelicocorp @Rona111 
We'll use the official version from OCA/website 
https://www.odoo.com/apps/modules/8.0/website_slides
https://github.com/OCA/website/tree/8.0/website_slides

**Comment by elicoidal** [comment]
Agree but to be retested with the module for QQ slides

**Comment by seb-elico** [comment]
LGTM

**Pull request closed without merging**
