### PR TITLE
[FIX] travis

### PR DESCRIPTION
**Pull request by noahzaozao**

### CODE REVIEW

**Comment by noahzaozao** [comment]
@elicoidal This might fix the travis status icon display issue in README.md

**Comment by elicoidal** [comment]
@noahzaozao Are you sure about that? OCA uses the free version as this is opensource but we use the paid version (.com)
@seb-elico

**Comment by noahzaozao** [comment]
@elicoidal https://travis-ci.com/Elico-Corp/odoo-addons problem is the link is now available for now

**Comment by elicoidal** [comment]
it looks  like you are right!

**Pull request merged**
