### PR TITLE
[IMP]10717 add module stock_inventory_import.

### PR DESCRIPTION
**Pull request by Rona111**

### CODE REVIEW

**Comment by elicoidal** [comment]
This module seems from the community: did we do anything to justify a new version in our repo?

**Comment by Rona111** [comment]
@elicoidal  This module if from OCA,and siyuan improved these module.
@siyuancn

**Comment by siyuancn** [comment]
The module from community used default_code to search the product, but the customer wants use the ean13 and some process didn't meet the customer's requirement. 
I modified the module to change the default_code to ean13 and fix some issues base on the customer's requirement.

**Comment by elicoidal** [comment]
I dont think we should bother then because this customer specific and not so generic. In this case, i f this is not really possible to add a separate new module we probably should not bother to commit

**Comment by siyuancn** [comment]
@elicoidal I agreed

**Comment by elicoidal** [comment]
@Rona111 Please cancel

**Comment by Rona111** [comment]
cancel.

**Pull request closed without merging**
